### ISSUE TITLE
AxiosError: url validation error: Request failed with status code 404

### ISSUE THREAD

**Issue by verschup76** [jakowenko/double-take-hassio-addons#18]
Hi,

Not sure if this is a deepstack or double-take issue, but I only see the error in double take log.
It seems it can connects for a short period, but then for no reason times-out.

Log:
22-09-15 17:26:21 info: processing Kitchen1: 1663256129.374423-7unxhg
22-09-15 17:26:43 info: done processing Kitchen1: 1663258360.425541-ozmrqi in 22.69 sec
22-09-15 17:26:43 info: {
  id: '1663258360.425541-ozmrqi',
  duration: 22.69,
  timestamp: '2022-09-15T16:26:43.757Z',
  attempts: 11,
  camera: 'Kitchen1',
  zones: [],
  matches: [],
  misses: []
}
22-09-15 17:27:07 info: processing Upstairs: 1663250294.313248-8knpek
22-09-15 17:28:27 info: processing Kitchen1: 1663259307.252954-ise4s8
22-09-15 17:28:29 info: processing Kitchen1: 1663259308.194997-ulfczx
22-09-15 17:28:29 info: processing kitchen1: db29d5d1-5fce-4cf0-955e-7b7c8e24fd70
22-09-15 17:28:29 error: AxiosError: url validation error: Request failed with status code 404
22-09-15 17:28:39 info: processing Upstairs: 1663259312.224723-gewikw
22-09-15 17:28:39 error: AxiosError: url validation error: Request failed with status code 404

Let me know if you need more info.

I am on the last version of HA.

Thanks,

Pim

**Comment by jakowenko** [comment]
Does this happen every time? This error means that the API failed to validate the URL of the image which is done before passing it to the detectors.

If `Kitchen1` is a Frigate camera, then it means the `latest` or `snapshot` image was failing. Do you have any other info about the config for this?

**Comment by verschup76** [comment]
Hi,
What other config info could be helpful, I have no idea so please let me know.

Thanks,

**Comment by jwagner0789** [comment]
I'm running into the same issue. What can I provide to help troubleshoot?

**Comment by skynan22** [comment]
Having the issue here, any ideas for solving it?

**Comment by rhamblen** [comment]
similar problem here!
I have 4 camera's same model, and set the same in frigate, yet one of them gives this error...

24-02-04 15:18:15 info: processing drive: 1707059895.712951-7tcjpx
24-02-04 15:18:17 error: stream error: Request failed with status code 404
AxiosError: Request failed with status code 404
    at settle (/double-take/api/node_modules/axios/dist/node/axios.cjs:1967:12)
    at IncomingMessage.handleStreamEnd (/double-take/api/node_modules/axios/dist/node/axios.cjs:3066:11)
    at IncomingMessage.emit (node:events:529:35)
    at endReadableNT (node:internal/streams/readable:1400:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Axios.request (/double-take/api/node_modules/axios/dist/node/axios.cjs:3877:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async module.exports.stream (/double-take/api/src/util/process.util.js:233:22)
    at async module.exports.polling (/double-take/api/src/util/process.util.js:34:22)
    at async Promise.all (index 1)
    at async module.exports.start (/double-take/api/src/controllers/recognize.controller.js:152:7)

**Comment by Utopia69** [comment]
Same here

info: processing gang: e6e60369-2df2-41a4-a984-b5aaac6fd41b
info: vanessa: queuing 6 file(s) for training
error: AxiosError: stream error: Request failed with status code 404
info: done processing gang: e6e60369-2df2-41a4-a984-b5aaac6fd41b in 2.82 sec
info: {
  id: 'e6e60369-2df2-41a4-a984-b5aaac6fd41b',
  duration: 2.82,
  timestamp: '2024-04-09T09:01:44.056Z',
  attempts: 1,
  camera: 'gang',
  zones: [],
  counts: { person: 0, match: 0, miss: 0, unknown: 0 },
  matches: [],
  misses: [],
  unknowns: []
}
error: compreface training error: No face is found in the given image
error: AxiosError: stream error: Request failed with status code 404
error: AxiosError: stream error: Request failed with status code 404
info: vanessa: training complete in 8.6 sec
error: AxiosError: stream error: Request failed with status code 404
error: AxiosError: stream error: Request failed with status code 404
error: AxiosError: stream error: Request failed with status code 404
